### ISSUE TITLE
Override default conf didn't work

### ISSUE THREAD

**Issue by Thomthomars** [dunglas/frankenphp-drupal#14]
Hi 
Sorry to create the first Issue related to a bug (I guess), maybe the problem come from my usage of this project.

## *Who* is the bug affecting?
My local dev. 

## *What* is affected by this bug?
My local can't run when I specify a different servername than locahost. 

## *When* does this occur?
As I mention in title, When I try to override variable SERVER_NAME in my docker-compose.yml this doesn't work at all.
To the point where I get  error just after build end.

## *Where* on the platform does it happen?

On my docker php container log I get this error : 
`{"level":"error","ts":1692351307.2484155,"logger":"http.acme_client","msg":"challenge failed","identifier":"test-project.fr","challenge_type":"tls-alpn-01","problem":{"type":"urn:ietf:params:acme:error:dns","title":"","detail":"DNS problem: NXDOMAIN looking up A for test-project.fr - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for test-project.fr - check that a DNS record exists for this domain","instance":"","subproblems":[]}}
2023-08-18 11:35:07 {"level":"error","ts":1692351307.2484634,"logger":"http.acme_client","msg":"validating authorization","identifier":"test-project.fr","problem":{"type":"urn:ietf:params:acme:error:dns","title":"","detail":"DNS problem: NXDOMAIN looking up A for test-project.fr - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for test-project.fr - check that a DNS record exists for this domain","instance":"","subproblems":[]},"order":"https://acme-v02.api.letsencrypt.org/acme/order/1263929236/202381515056","attempt":1,"max_attempts":3}`

`{"level":"error","ts":1692350579.8766775,"logger":"tls.obtain","msg":"will retry","error":"[je-suis-un-test.com] Obtain: [je-suis-un-test.com] solving challenge: je-suis-un-test.com: [je-suis-un-test.com] authorization failed: HTTP 0  -  (ca=https://acme.zerossl.com/v2/DV90)","attempt":1,"retrying_in":60,"elapsed":13.03427109,"max_duration":2592000}`

## *How* do we replicate the issue?
In a docker-compose file, specify server_name custom. 
exemple : 
```
  drupal:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /app/public/modules
      - /app/public/profiles
      - /app/public/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /app/public/sites
    restart: always
    environment:
      SERVER_NAME: test-project.fr
```

## Expected behavior (i.e. solution)
the url specify must return http code 200 and content.

## Other Comments

As I say, maybe it's my poor understanding of Caddy and how it's work. 
I have another problem related to xdebug that isn't working neither. maybe I can keep that for a second issue. 

BTW : I have to say that my local performance are greatly improve by using the project :)
